# Generated by Django 5.0.12 on 2025-07-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='project_thumbnails/')),
                ('case_study', models.TextField()),
                ('github_link', models.URLField()),
                ('live_demo_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
